access-token:
 private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
 public:  ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
 
refresh-token:
 private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
 public:  ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
 
spring:
 profiles:
   active: dev
 data:
   mongodb:
     uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@spring-security.jtlbfe7.mongodb.net/
     database: ${MONGODB_DB}
logging:
  level:
    org.springframework.security: DEBUG
    
server:
  port : 8000
 